name: E2E Template

on:
  workflow_call:
    inputs:
      sfra-version:
        required: true
        type: string
      node-version:
        required: true
        type: string
      code-version:
        required: true
        type: string
      is-main-branch:
        required: true
        type: boolean
    secrets:
      SFCC_USERNAME:
        required: true
      SFCC_PASSWORD:
        required: true
      SERVICE_ACCOUNT_SSH_KEY:
        required: true
      SFCC_HOSTNAME:
        required: true
      SFCC_CODE_VERSION:
        required: true
      SFCC_STOREFRONT_URL:
        required: true
      SANDBOX_HTTP_AUTH_USERNAME:
        required: true
      SANDBOX_HTTP_AUTH_PASSWORD:
        required: true
      PAYPAL_USERNAME:
        required: true
      PAYPAL_PASSWORD:
        required: true
      AMAZONPAY_USERNAME:
        required: true
      AMAZONPAY_PASSWORD:
        required: true

jobs:
  setup-and-test:
    runs-on: ubuntu-22.04
    timeout-minutes: 30
    steps:
      - name: Checkout SFRA code
        uses: actions/checkout@v4
        with:
          repository: SalesforceCommerceCloud/storefront-reference-architecture
          ref: ${{ inputs.sfra-version }}
          ssh-key: ${{ secrets.SERVICE_ACCOUNT_SSH_KEY }}
          path: storefront-reference-architecture

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ inputs.node-version }}
      - name: Checkout Adyen integration
        uses: actions/checkout@v4
        with:
          path: adyen-salesforce-commerce-cloud
      - name: Install SFRA dependencies
        working-directory: storefront-reference-architecture
        run: npm install
      - name: Install Adyen SFCC dependencies
        working-directory: adyen-salesforce-commerce-cloud
        run: npm install
      - name: Create dw.json
        working-directory: adyen-salesforce-commerce-cloud
        run: |
          echo '{
            "username": "${{ secrets.SFCC_USERNAME }}",
            "password": "${{ secrets.SFCC_PASSWORD }}",
            "hostname": "${{ secrets.SFCC_HOSTNAME }}",
            "code-version": "${{ secrets.SFCC_CODE_VERSION }}"
          }' > dw.json
      - name: Transpile the code
        working-directory: adyen-salesforce-commerce-cloud
        run: npm run transpile
      - name: Compile the code
        working-directory: adyen-salesforce-commerce-cloud
        run: npm run compile:js
      - name: Build the cartridge
        working-directory: adyen-salesforce-commerce-cloud
        run: npm run uploadCartridge > output.txt
      - name: Check build result
        working-directory: adyen-salesforce-commerce-cloud
        run: npm run check-build:sfra
      - name: Install e2e test dependencies
        working-directory: adyen-salesforce-commerce-cloud/tests/playwright/
        run: npm install
      - name: Setup Playwright dependencies
        working-directory: adyen-salesforce-commerce-cloud/tests/playwright/
        run: npx playwright install --with-deps
      - name: Run E2E Tests (Full)
        if: inputs.is-main-branch == true
        working-directory: adyen-salesforce-commerce-cloud/tests/playwright/
        run: npm run test:ci
        env:
          SANDBOX_HTTP_AUTH_USERNAME: ${{ secrets.SANDBOX_HTTP_AUTH_USERNAME }}
          SANDBOX_HTTP_AUTH_PASSWORD: ${{ secrets.SANDBOX_HTTP_AUTH_PASSWORD }}
          PAYPAL_USERNAME: ${{ secrets.PAYPAL_USERNAME }}
          PAYPAL_PASSWORD: ${{ secrets.PAYPAL_PASSWORD }}
          AMAZONPAY_USERNAME: ${{ secrets.AMAZONPAY_USERNAME }}
          AMAZONPAY_PASSWORD: ${{ secrets.AMAZONPAY_PASSWORD }}
          SFRA_VERSION: ${{ inputs.sfra-version }}
          SFCC_HOSTNAME: ${{ secrets.SFCC_STOREFRONT_URL }}
      - name: Run E2E Tests (Quick)
        if: inputs.is-main-branch == false
        working-directory: adyen-salesforce-commerce-cloud/tests/playwright/
        run: npm run test:ci:quick
        env:
          SANDBOX_HTTP_AUTH_USERNAME: ${{ secrets.SANDBOX_HTTP_AUTH_USERNAME }}
          SANDBOX_HTTP_AUTH_PASSWORD: ${{ secrets.SANDBOX_HTTP_AUTH_PASSWORD }}
          PAYPAL_USERNAME: ${{ secrets.PAYPAL_USERNAME }}
          PAYPAL_PASSWORD: ${{ secrets.PAYPAL_PASSWORD }}
          AMAZONPAY_USERNAME: ${{ secrets.AMAZONPAY_USERNAME }}
          AMAZONPAY_PASSWORD: ${{ secrets.AMAZONPAY_PASSWORD }}
          SFRA_VERSION: ${{ inputs.sfra-version }}
          SFCC_HOSTNAME: ${{ secrets.SFCC_STOREFRONT_URL }}
      - name: Archive Playwright report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report-${{ inputs.sfra-version }}
          path: adyen-salesforce-commerce-cloud/tests/playwright/playwright-report