name: Metadata upload

on:
  pull_request:

permissions:
  contents: read

jobs:
  upload-sfra5:
    uses: ./.github/workflows/metadata-upload-template.yml
    with:
      sfcc_hostname: ${{ secrets.SFCC_STOREFRONT_URL_SFRA5 }}
      node_version: '16'
    secrets: inherit
  upload-sfra6:
    uses: ./.github/workflows/metadata-upload-template.yml
    with:
      sfcc_hostname: ${{ secrets.SFCC_STOREFRONT_URL_SFRA6 }}
      node_version: '16'
    secrets: inherit
  upload-sfra7:
    uses: ./.github/workflows/metadata-upload-template.yml
    with:
      sfcc_hostname: ${{ secrets.SFCC_STOREFRONT_URL_SFRA7 }}
      node_version: '18'
    secrets: inherit
