name: Upload Release Template

on:
  workflow_call:
    inputs:
      sfra_version:
        required: true
        type: string
      node_version:
        required: true
        type: string
    secrets:
      SFCC_HOSTNAME:
        required: true
      CODE_VERSION:
        required: true
      SFCC_USERNAME:
        required: true
      SFCC_PASSWORD:
        required: true
      SFCC_CLIENT_ID:
        required: true
      SFCC_CLIENT_SECRET:
        required: true
      SERVICE_ACCOUNT_SSH_KEY:
        required: true

jobs:
  upload:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Checkout SFRA code
        uses: actions/checkout@v4
        with:
          repository: SalesforceCommerceCloud/storefront-reference-architecture
          ref: ${{ inputs.sfra_version }}
          ssh-key: ${{ secrets.SERVICE_ACCOUNT_SSH_KEY }}
          path: storefront-reference-architecture
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ inputs.node_version }}
      - name: Checkout Adyen Cartridge
        uses: actions/checkout@v4
        with:
          path: adyen-salesforce-commerce-cloud
      - name: Install SFRA dependencies
        working-directory: storefront-reference-architecture
        run: npm install
      - name: Install Adyen SFCC dependencies
        working-directory: adyen-salesforce-commerce-cloud
        run: npm install
      - name: Create dw.json file
        working-directory: adyen-salesforce-commerce-cloud
        run: |
          echo '{
            "username": "${{ secrets.SFCC_USERNAME }}",
            "password": "${{ secrets.SFCC_PASSWORD }}",
            "hostname": "${{ secrets.SFCC_HOSTNAME }}",
            "code-version": "${{ secrets.CODE_VERSION }}"
          }' >> dw.json
      - name: Transpile the code
        working-directory: adyen-salesforce-commerce-cloud
        run: npm run transpile
      - name: Compile the code
        working-directory: adyen-salesforce-commerce-cloud
        run: npm run compile:js
      - name: Build the cartridge
        working-directory: adyen-salesforce-commerce-cloud
        run: npm run uploadCartridge > output-sfra.txt
      - name: Check build result
        working-directory: adyen-salesforce-commerce-cloud
        run: npm run check-build:sfra
      - name: Install Salesforce CLI
        run: npm install -g sfcc-ci
      - name: Zip site_import
        working-directory: adyen-salesforce-commerce-cloud/metadata
        run: zip -r $GITHUB_WORKSPACE/site_import.zip site_import
      - name: Upload the metadata to the sandbox
        working-directory: adyen-salesforce-commerce-cloud/metadata
        run: |
          sfcc-ci client:auth '${{ secrets.SFCC_CLIENT_ID }}' '${{ secrets.SFCC_CLIENT_SECRET }}'
          sfcc-ci instance:upload $GITHUB_WORKSPACE/site_import.zip -i "${{ secrets.SFCC_HOSTNAME }}"
      - name: Import the metadata to the sandbox
        working-directory: adyen-salesforce-commerce-cloud/metadata
        run: |
          sfcc-ci instance:import site_import.zip -i "${{ secrets.SFCC_HOSTNAME }}" -s