name: Release upload

on:
  pull_request:

permissions:
  contents: read

jobs:
  upload-release:
    if: |
      github.event_name == 'pull_request' &&
      contains(github.head_ref, 'improvement') &&
      github.event.pull_request.base.ref == 'develop'
    runs-on: ubuntu-latest
    timeout-minutes: 5
    strategy:
      fail-fast: false
      matrix:
        include:
          - sfra_version: 'v6.1.0'
            node_version: '14'
            sfcc_hostname: ${{ secrets.SFCC_STOREFRONT_URL_004 }}
          - sfra_version: 'v6.1.0'
            node_version: '14'
            sfcc_hostname: ${{ secrets.SFCC_STOREFRONT_URL_006 }}
          - sfra_version: 'v5.3.0'
            node_version: '14'
            sfcc_hostname: ${{ secrets.SFCC_STOREFRONT_URL_007 }}
          - sfra_version: 'v6.1.0'
            node_version: '14'
            sfcc_hostname: ${{ secrets.SFCC_STOREFRONT_URL_019 }}
          - sfra_version: 'v6.1.0'
            node_version: '14'
            sfcc_hostname: ${{ secrets.SFCC_STOREFRONT_URL_020 }}
          - sfra_version: 'v6.1.0'
            node_version: '14'
            sfcc_hostname: ${{ secrets.SFCC_STOREFRONT_URL_022 }}

    steps:
      - name: Checkout SFRA code
        uses: actions/checkout@v4
        with:
          repository: SalesforceCommerceCloud/storefront-reference-architecture
          ref: ${{ matrix.sfra_version }}
          ssh-key: ${{ secrets.SERVICE_ACCOUNT_SSH_KEY }}
          path: storefront-reference-architecture
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node_version }}
      - name: Checkout
        uses: actions/checkout@v4
        with:
          path: adyen-salesforce-commerce-cloud
      - name: Install SFRA dependencies
        working-directory: storefront-reference-architecture
        run: npm install
      - name: Install Adyen dependencies
        working-directory: adyen-salesforce-commerce-cloud
        run: npm install
      - name: Create dw.json file
        working-directory: adyen-salesforce-commerce-cloud
        run: |
          echo '{
            "username": "${{ secrets.SFCC_USERNAME }}",
            "password": "${{ secrets.SFCC_PASSWORD }}",
            "hostname": "${{ matrix.sfcc_hostname }}",
            "code-version": "${{ secrets.SFCC_CODE_VERSION_COMMON }}"
          }' >> dw.json
      - name: Transpile code
        working-directory: adyen-salesforce-commerce-cloud
        run: npm run transpile
      - name: Compile code
        working-directory: adyen-salesforce-commerce-cloud
        run: npm run compile:js
      - name: Build cartridge
        working-directory: adyen-salesforce-commerce-cloud
        run: npm run uploadCartridge > output-sfra.txt
      - name: Check build result
        working-directory: adyen-salesforce-commerce-cloud
        run: npm run check-build:sfra
      - name: Install Salesforce CLI
        run: npm install -g sfcc-ci
      - name: Zip site_import
        working-directory: adyen-salesforce-commerce-cloud/metadata
        run: zip -r $GITHUB_WORKSPACE/site_import.zip site_import
      - name: Upload metadata
        run: |
          sfcc-ci client:auth '${{ secrets.SFCC_CLIENT_ID }}' '${{ secrets.SFCC_CLIENT_SECRET }}'
          sfcc-ci instance:upload $GITHUB_WORKSPACE/site_import.zip -i "${{ matrix.sfcc_hostname }}"
      - name: Import metadata
        run: |
          sfcc-ci instance:import site_import.zip -i "${{ matrix.sfcc_hostname }}" -s
